import os
import yt_dlp
from pydub import AudioSegment


# ============================================================
# CONFIGURATION
# ============================================================

DOWNLOAD_DIR = "downloads"

os.makedirs(DOWNLOAD_DIR, exist_ok=True)


# ============================================================
# 1. DOWNLOAD YOUTUBE AUDIO
# ============================================================

def download_youtube_audio(url: str) -> str:
    """
    Download YouTube audio using format 140.

    Format 140:
        M4A
        Audio only
        ~129 kbps

    Returns:
        Path to downloaded M4A file.
    """

    output_path = os.path.join(
        DOWNLOAD_DIR,
        "%(title)s.%(ext)s"
    )

    ydl_opts = {
        # IMPORTANT:
        # Format 140 was successfully tested from CLI.
        "format": "140",

        "outtmpl": output_path,

        # Don't download playlists
        "noplaylist": True,

        "quiet": False,

        # YouTube JavaScript challenge support
        "js_runtimes": {
            "deno": {}
        },

        # yt-dlp EJS
        "remote_components": [
            "ejs:github"
        ],
    }

    print()
    print("========================================")
    print("DOWNLOADING YOUTUBE AUDIO")
    print("========================================")
    print(f"URL: {url}")
    print()

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:

        info = ydl.extract_info(
            url,
            download=True
        )

        # Get the exact filename generated by yt-dlp
        audio_file = ydl.prepare_filename(info)

    # --------------------------------------------------------
    # Format 140 should produce M4A
    # --------------------------------------------------------

    if not os.path.exists(audio_file):

        # Safety fallback
        possible_m4a = os.path.splitext(audio_file)[0] + ".m4a"

        if os.path.exists(possible_m4a):
            audio_file = possible_m4a

        else:
            raise FileNotFoundError(
                f"Downloaded audio file not found.\n"
                f"Expected: {audio_file}"
            )

    print()
    print("DOWNLOAD SUCCESSFUL")
    print(f"Audio file: {audio_file}")

    return audio_file


# ============================================================
# 2. CONVERT AUDIO / VIDEO TO WAV
# ============================================================

def convert_to_wav(input_path: str) -> str:
    """
    Convert an audio/video file to WAV.

    Output:
        Mono
        16 kHz
        WAV

    Supported examples:
        MP4
        MP3
        M4A
        WEBM
        FLAC
        AAC
        WAV
        OGG
        OPUS
        MOV
        MKV
    """

    if not os.path.isfile(input_path):
        raise FileNotFoundError(
            f"File not found: {input_path}"
        )

    print()
    print("========================================")
    print("CONVERTING TO WAV")
    print("========================================")

    print(f"Input: {input_path}")

    # Load audio using FFmpeg through pydub
    audio = AudioSegment.from_file(input_path)

    # --------------------------------------------------------
    # Normalize audio
    # --------------------------------------------------------

    audio = audio.set_channels(1)
    audio = audio.set_frame_rate(16000)

    # --------------------------------------------------------
    # Output filename
    # --------------------------------------------------------

    output_path = (
        os.path.splitext(input_path)[0]
        + "_converted.wav"
    )

    # --------------------------------------------------------
    # Export WAV
    # --------------------------------------------------------

    audio.export(
        output_path,
        format="wav"
    )

    if not os.path.exists(output_path):
        raise FileNotFoundError(
            f"WAV conversion failed: {output_path}"
        )

    print(f"Output: {output_path}")
    print("WAV conversion successful")

    return output_path


# ============================================================
# 3. CHUNK AUDIO
# ============================================================

def chunk_audio(
    wav_path: str,
    chunk_minutes: int = 10
) -> list:
    """
    Split WAV audio into smaller chunks.

    Default:
        10 minutes per chunk.

    Returns:
        List of chunk file paths.
    """

    if not os.path.isfile(wav_path):
        raise FileNotFoundError(
            f"WAV file not found: {wav_path}"
        )

    print()
    print("========================================")
    print("CREATING AUDIO CHUNKS")
    print("========================================")

    audio = AudioSegment.from_wav(wav_path)

    chunk_ms = chunk_minutes * 60 * 1000

    chunks = []

    base_name = os.path.splitext(wav_path)[0]

    # --------------------------------------------------------
    # Create chunks
    # --------------------------------------------------------

    for i, start in enumerate(
        range(0, len(audio), chunk_ms)
    ):

        end = start + chunk_ms

        chunk = audio[start:end]

        chunk_path = (
            f"{base_name}_chunk_{i}.wav"
        )

        chunk.export(
            chunk_path,
            format="wav"
        )

        chunks.append(chunk_path)

        print(
            f"Chunk {i}: {chunk_path}"
        )

    print()
    print("----------------------------------------")
    print(f"Chunk duration: {chunk_minutes} minutes")
    print(f"Total chunks  : {len(chunks)}")
    print("----------------------------------------")

    return chunks


# ============================================================
# 4. COMPLETE AUDIO PROCESSING PIPELINE
# ============================================================

def process_audio_file(
    input_path: str,
    chunk_minutes: int = 10
) -> list:
    """
    Complete audio processing pipeline.

    Input:
        M4A / MP3 / MP4 / etc.

    Pipeline:

        Input
          ↓
        Convert to WAV
          ↓
        Mono
          ↓
        16 kHz
          ↓
        Split into chunks
          ↓
        Return chunk paths
    """

    # --------------------------------------------------------
    # STEP 1: Convert to WAV
    # --------------------------------------------------------

    wav_file = convert_to_wav(
        input_path
    )

    # --------------------------------------------------------
    # STEP 2: Create chunks
    # --------------------------------------------------------

    chunks = chunk_audio(
        wav_file,
        chunk_minutes
    )

    return chunks


# ============================================================
# 5. MAIN
# ============================================================

if __name__ == "__main__":

    try:

        # ====================================================
        # YOUTUBE URL
        # ====================================================

        youtube_url = (
            "https://www.youtube.com/watch?v=TbbSJrY5GqQ"
        )

        # ====================================================
        # STEP 1: DOWNLOAD AUDIO
        # ====================================================

        downloaded_audio = download_youtube_audio(
            youtube_url
        )

        # ====================================================
        # STEP 2: CONVERT + NORMALIZE + CHUNK
        # ====================================================

        chunks = process_audio_file(
            downloaded_audio,
            chunk_minutes=10
        )

        # ====================================================
        # FINAL RESULT
        # ====================================================

        print()
        print("========================================")
        print("AUDIO PROCESSING SUCCESSFUL")
        print("========================================")

        print()
        print("CHUNKS READY FOR TRANSCRIPTION:")
        print()

        for i, chunk in enumerate(chunks):

            print(
                f"Chunk {i}: {chunk}"
            )

        print()
        print("----------------------------------------")
        print(f"Total chunks: {len(chunks)}")
        print("----------------------------------------")

    except Exception as e:

        print()
        print("========================================")
        print("ERROR")
        print("========================================")

        print(
            f"{type(e).__name__}: {e}"
        )